version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    container_name: bookmanager-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: pnpm dev --host

networks:
  default:
    name: bookmanager-network